# Generated by Django 6.0.7 on 2026-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sharednote',
            name='uniq_shared_note_per_path',
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='path',
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='user',
        ),
    ]
