# Generated by Django 6.0.7 on 2026-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_sharednote_uniq_shared_note_per_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaCompartida',
            fields=[
                ('token', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=600, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notes_carpetacompartida',
            },
        ),
    ]
