# Generated by Django 6.0.7 on 2026-07-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invitetoken',
            name='used_by',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='InviteToken',
        ),
    ]
