# Generated by Django 6.0.7 on 2026-07-25 12:30

from django.db import migrations, models


def make_existing_users_owners(apps, schema_editor):
    """Las cuentas que ya existían son del dueño del sitio.

    El default del campo es `viewer` (lo prudente para un alta nueva), pero
    aplicado tal cual dejaría al propietario sin permiso de escritura en su
    propia bóveda: todo lo anterior a esta migración es suyo.
    """
    apps.get_model("accounts", "User").objects.update(role="owner")


def noop(apps, schema_editor):
    """Marcha atrás: la columna entera desaparece, no hay nada que revertir."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('editor', 'Lectura y escritura'), ('viewer', 'Sólo lectura')], default='viewer', max_length=10),
        ),
        migrations.RunPython(make_existing_users_owners, noop),
    ]
