# Generated by Django 6.0.7 on 2026-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro'), ('dracula', 'Drácula'), ('pink', 'Rosa'), ('gold', 'Dorado')], default='dark', max_length=16),
        ),
    ]
