# Generated by Django 6.0.7 on 2026-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tema_dark_cristal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sso_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
