# Generated by Django 6.0.7 on 2026-08-12 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tema_cafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoBoveda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('editor', 'Lectura y escritura'), ('viewer', 'Sólo lectura')], default='viewer', max_length=10)),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.DateTimeField(blank=True, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_dados', to=settings.AUTH_USER_MODEL)),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accesos_boveda',
                'constraints': [models.UniqueConstraint(fields=('dueno', 'invitado'), name='un_acceso_por_pareja')],
            },
        ),
    ]
