# Generated by Django 6.0.7 on 2026-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_tema_crystal'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoboveda',
            name='ambito',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
